export default function Head() {
  return (
    <>
      <title>MatchMaster</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/logo-isolated.svg" />
    </>
  );
}
